resilience4j:
  retry:
    instances:
      percentageServiceRetry:
        maxAttempts: 3                  # Máximo 3 intentos ante fallos
        waitDuration: 1s                # Espera de 1 segundo entre cada intento
        enableExponentialBackoff: true  # Incrementa progresivamente el tiempo de espera (opcional pero recomendado)
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.RuntimeException  # O la excepción específica que lance tu cliente HTTP mock
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/calculator_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha